name: Build Ubuntu 22.04 Image

on:
  workflow_dispatch

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    
    - name: 'Navigate to Workspace'
      run: cd $GITHUB_WORKSPACE

    - name: 'dir just for debug'
      run: |
        dir

    - name: 'Build Ubuntu 2204 Image'
      shell: pwsh
      run: |
        git clone https://github.com/actions/virtual-environments.git
        cd ./virtual-environments
        Import-Module .\helpers\GenerateResourcesAndImage.ps1
        #GenerateResourcesAndImage -SubscriptionId ${{ secrets.SUBSCRIPTIONID }} -ResourceGroupName ${{ env.UbuntuImageResourceGroup }} -ImageGenerationRepositoryRoot "$pwd" -ImageType Ubuntu2204 -AzureLocation ${{ env.Region }} -AzureClientId ${{ secrets.APPLICATIONID }} -AzureClientSecret ${{ secrets.SECRET }} -AzureTenantId ${{ secrets.TENANTID }}


    - name: 'Export Image'
      shell: pwsh
      run: |
        # env for source image
        $subscriptionId="${{ secrets.SUBSCRIPTIONID }}"
        $resourceGroup="${{ vars.UbuntuImageResourceGroup }}"
        $imageName="Runner-Image-Ubuntu2204"
        
        # env for target gallery
        $newGalleryName="${{ vars.GALERYNAME }}"
        $newGalleryResourceGroup="${{ vars.GALERYNAME }}"
        $location="${{ vars.Region }}"
        $imageDefinition=$imageName
        
        
        # Login to Azure
        az login --service-principal -u ${{ secrets.APPLICATIONID }} -p ${{ secrets.SECRET }} --tenant ${{ secrets.TENANTID }}
        
        # Set the subscription context
        az account set --subscription $subscriptionId
        
        # Create a new resource group for the gallery if it doesn't exist
        az group create --name $newGalleryResourceGroup --location $location
        
        # Create a new image gallery
        az sig create --resource-group $newGalleryResourceGroup --gallery-name $newGalleryName --location $location
        
        # Create an image definition in the gallery
        az sig image-definition create --resource-group $newGalleryResourceGroup --gallery-name $newGalleryName --gallery-image-definition $imageDefinition --os-type Windows --publisher myPublisher --offer myOffer --sku mySku --os-state generalized
        
        # Finally, copy the image to the gallery
        
        az sig image-version create --resource-group $newGalleryResourceGroup --gallery-name $newGalleryName --gallery-image-definition $imageDefinition --gallery-image-version 1.0.0 --location $location --managed-image "/subscriptions/$subscriptionId/resourceGroups/$resourceGroup/providers/Microsoft.Compute/images/$imageName"
